### ISSUE TITLE
3D Modelling issues

### ISSUE THREAD

**Issue by FirstOfficerDelta** [FirstOfficerDelta/747-8i#1]
~~1. Aircraft flaps, ailerons and flaperons have very weird normals.~~
![image](https://user-images.githubusercontent.com/66116718/136831762-aafd9aed-cecd-4cb0-b05d-7afe50f1e44b.png)
~~2. Elevators appear in two instead of one.~~
![image](https://user-images.githubusercontent.com/66116718/136831290-94449f9b-9a8b-45d2-aa53-ae69f60cf74d.png)
~~3. Cockpit having no roof from the inside~~
![image](https://user-images.githubusercontent.com/66116718/136831263-d982246c-c98c-409b-badd-ec660e59c419.png)
4. Cockpit visible when the nose cargo door is open
![image](https://user-images.githubusercontent.com/66116718/136831905-c234382f-dcb9-4daf-8209-a7ff4e04f776.png)
5. Update the lighting effects (especially on the cargo hold)
6. Fix the chromium shader on the rim of the engines
7. Fix the fan blade texture to only show the fan blade and not what is behind it.
8. Fix the size of the lights when the aircraft goes far.
9. Redo the doors based on the Airplane Characteristics for Airport Planning (https://www.boeing.com/resources/boeingdotcom/commercial/airports/acaps/747_8.pdf)

**Comment by Sadia2000** [comment]
Is this for the 748F?

**Comment by Sadia2000** [comment]
hmm... interesting, never saw anything like that :/
